### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by MrChillDev** [zf9/Keyauth_csgo#4]
Gets stuck on waiting for CSGO

**Comment by MrChillDev** [comment]
Even tho its opened

**Comment by zf9** [comment]
This is because csgo has updated their window title. You will be able to find the new one using Visual Sudio - Spy++

**Comment by MrChillDev** [comment]
I fixed it so thanks

**Comment by MrChillDev** [comment]
but you got discord

**Comment by MrChillDev** [comment]
becuase i need some help making another keyauth loader

**Comment by MrChillDev** [comment]
mine is hssd#3688

**Comment by zf9** [comment]
Yea I added you - ZF9#7655

**Comment by MrChillDev** [comment]
k

**Comment by MrChillDev** [comment]
also i was wondering
if you could make a gta5 injector/loader
